"""
stock_list.py
─────────────────────────────────────────────────────────────────────────────
Comprehensive list of NSE-listed equity stocks used by the autocomplete
widget in the Brokerage & MTF Interest Calculator.

Format: list of (NSE_SYMBOL, "Company Name") tuples.

Coverage:
  • Nifty 50
  • Nifty Next 50
  • Nifty Midcap 150
  • Nifty Smallcap 250 (popular constituents)
  • Other actively traded NSE equities

Symbols follow the official NSE ticker notation.
"""

NSE_STOCKS: list[tuple[str, str]] = [

    # ── Nifty 50 ──────────────────────────────────────────────────────────────
    ("ADANIENT",    "Adani Enterprises Ltd"),
    ("ADANIPORTS",  "Adani Ports & SEZ Ltd"),
    ("APOLLOHOSP",  "Apollo Hospitals Enterprise Ltd"),
    ("ASIANPAINT",  "Asian Paints Ltd"),
    ("AXISBANK",    "Axis Bank Ltd"),
    ("BAJAJ-AUTO",  "Bajaj Auto Ltd"),
    ("BAJAJFINSV",  "Bajaj Finserv Ltd"),
    ("BAJFINANCE",  "Bajaj Finance Ltd"),
    ("BHARTIARTL",  "Bharti Airtel Ltd"),
    ("BPCL",        "Bharat Petroleum Corporation Ltd"),
    ("BRITANNIA",   "Britannia Industries Ltd"),
    ("CIPLA",       "Cipla Ltd"),
    ("COALINDIA",   "Coal India Ltd"),
    ("DIVISLAB",    "Divi's Laboratories Ltd"),
    ("DRREDDY",     "Dr. Reddy's Laboratories Ltd"),
    ("EICHERMOT",   "Eicher Motors Ltd"),
    ("GRASIM",      "Grasim Industries Ltd"),
    ("HCLTECH",     "HCL Technologies Ltd"),
    ("HDFCBANK",    "HDFC Bank Ltd"),
    ("HDFCLIFE",    "HDFC Life Insurance Company Ltd"),
    ("HEROMOTOCO",  "Hero MotoCorp Ltd"),
    ("HINDALCO",    "Hindalco Industries Ltd"),
    ("HINDUNILVR",  "Hindustan Unilever Ltd"),
    ("ICICIBANK",   "ICICI Bank Ltd"),
    ("INDUSINDBK",  "IndusInd Bank Ltd"),
    ("INFY",        "Infosys Ltd"),
    ("ITC",         "ITC Ltd"),
    ("JSWSTEEL",    "JSW Steel Ltd"),
    ("KOTAKBANK",   "Kotak Mahindra Bank Ltd"),
    ("LT",          "Larsen & Toubro Ltd"),
    ("M&M",         "Mahindra & Mahindra Ltd"),
    ("MARUTI",      "Maruti Suzuki India Ltd"),
    ("NESTLEIND",   "Nestle India Ltd"),
    ("NTPC",        "NTPC Ltd"),
    ("ONGC",        "Oil & Natural Gas Corporation Ltd"),
    ("POWERGRID",   "Power Grid Corporation of India Ltd"),
    ("RELIANCE",    "Reliance Industries Ltd"),
    ("SBILIFE",     "SBI Life Insurance Company Ltd"),
    ("SBIN",        "State Bank of India"),
    ("SUNPHARMA",   "Sun Pharmaceutical Industries Ltd"),
    ("TATACONSUM",  "Tata Consumer Products Ltd"),
    ("TATAMOTORS",  "Tata Motors Ltd"),
    ("TATASTEEL",   "Tata Steel Ltd"),
    ("TCS",         "Tata Consultancy Services Ltd"),
    ("TECHM",       "Tech Mahindra Ltd"),
    ("TITAN",       "Titan Company Ltd"),
    ("ULTRACEMCO",  "UltraTech Cement Ltd"),
    ("UPL",         "UPL Ltd"),
    ("WIPRO",       "Wipro Ltd"),
    ("ZOMATO",      "Zomato Ltd"),

    # ── Nifty Next 50 ─────────────────────────────────────────────────────────
    ("ABB",         "ABB India Ltd"),
    ("ADANIGREEN",  "Adani Green Energy Ltd"),
    ("ADANIPOWER",  "Adani Power Ltd"),
    ("AMBUJACEM",   "Ambuja Cements Ltd"),
    ("ATGL",        "Adani Total Gas Ltd"),
    ("AUROPHARMA",  "Aurobindo Pharma Ltd"),
    ("AWL",         "Adani Wilmar Ltd"),
    ("BAJAJHLDNG",  "Bajaj Holdings & Investment Ltd"),
    ("BANKBARODA",  "Bank of Baroda"),
    ("BERGEPAINT",  "Berger Paints India Ltd"),
    ("BEL",         "Bharat Electronics Ltd"),
    ("BHEL",        "Bharat Heavy Electricals Ltd"),
    ("BOSCHLTD",    "Bosch Ltd"),
    ("CANBK",       "Canara Bank"),
    ("CHOLAFIN",    "Cholamandalam Investment and Finance Company Ltd"),
    ("COLPAL",      "Colgate-Palmolive (India) Ltd"),
    ("DMART",       "Avenue Supermarts Ltd"),
    ("GAIL",        "GAIL (India) Ltd"),
    ("GODREJCP",    "Godrej Consumer Products Ltd"),
    ("HAL",         "Hindustan Aeronautics Ltd"),
    ("HAVELLS",     "Havells India Ltd"),
    ("ICICIGI",     "ICICI Lombard General Insurance Company Ltd"),
    ("ICICIPRULI",  "ICICI Prudential Life Insurance Company Ltd"),
    ("INDIGO",      "InterGlobe Aviation Ltd"),
    ("IOC",         "Indian Oil Corporation Ltd"),
    ("IRCTC",       "Indian Railway Catering & Tourism Corporation Ltd"),
    ("LICI",        "Life Insurance Corporation of India"),
    ("LTFH",        "L&T Finance Ltd"),
    ("LTIM",        "LTIMindtree Ltd"),
    ("LTTS",        "L&T Technology Services Ltd"),
    ("MARICO",      "Marico Ltd"),
    ("MUTHOOTFIN",  "Muthoot Finance Ltd"),
    ("NAUKRI",      "Info Edge (India) Ltd"),
    ("PIDILITIND",  "Pidilite Industries Ltd"),
    ("PIIND",       "PI Industries Ltd"),
    ("PFC",         "Power Finance Corporation Ltd"),
    ("PNB",         "Punjab National Bank"),
    ("RECLTD",      "REC Ltd"),
    ("SHREECEM",    "Shree Cement Ltd"),
    ("SIEMENS",     "Siemens Ltd"),
    ("SRF",         "SRF Ltd"),
    ("TATAPOWER",   "Tata Power Company Ltd"),
    ("TORNTPHARM",  "Torrent Pharmaceuticals Ltd"),
    ("TRENT",       "Trent Ltd"),
    ("VEDL",        "Vedanta Ltd"),
    ("VBL",         "Varun Beverages Ltd"),
    ("ZYDUSLIFE",   "Zydus Lifesciences Ltd"),

    # ── Nifty Midcap 150 ──────────────────────────────────────────────────────
    ("AAVAS",       "Aavas Financiers Ltd"),
    ("ABCAPITAL",   "Aditya Birla Capital Ltd"),
    ("ABFRL",       "Aditya Birla Fashion and Retail Ltd"),
    ("ACC",         "ACC Ltd"),
    ("AFFLE",       "Affle (India) Ltd"),
    ("AJANTPHARM",  "Ajanta Pharmaceuticals Ltd"),
    ("ALKEM",       "Alkem Laboratories Ltd"),
    ("APOLLOTYRE",  "Apollo Tyres Ltd"),
    ("ATUL",        "Atul Ltd"),
    ("AUBANK",      "AU Small Finance Bank Ltd"),
    ("BATAINDIA",   "Bata India Ltd"),
    ("BIOCON",      "Biocon Ltd"),
    ("BSE",         "BSE Ltd"),
    ("CANFINHOME",  "Can Fin Homes Ltd"),
    ("CEATLTD",     "CEAT Ltd"),
    ("CGPOWER",     "CG Power and Industrial Solutions Ltd"),
    ("COFORGE",     "Coforge Ltd"),
    ("CONCOR",      "Container Corporation of India Ltd"),
    ("CROMPTON",    "Crompton Greaves Consumer Electricals Ltd"),
    ("CUMMINSIND",  "Cummins India Ltd"),
    ("DATAPATTNS",  "Data Patterns (India) Ltd"),
    ("DEEPAKNTR",   "Deepak Nitrite Ltd"),
    ("ELGIEQUIP",   "Elgi Equipments Ltd"),
    ("EMAMILTD",    "Emami Ltd"),
    ("ENDURANCE",   "Endurance Technologies Ltd"),
    ("ESCORTS",     "Escorts Kubota Ltd"),
    ("EXIDEIND",    "Exide Industries Ltd"),
    ("FEDERALBNK",  "Federal Bank Ltd"),
    ("GLENMARK",    "Glenmark Pharmaceuticals Ltd"),
    ("GODREJPROP",  "Godrej Properties Ltd"),
    ("GRANULES",    "Granules India Ltd"),
    ("HINDPETRO",   "Hindustan Petroleum Corporation Ltd"),
    ("HUDCO",       "Housing and Urban Development Corporation Ltd"),
    ("IDFCFIRSTB",  "IDFC First Bank Ltd"),
    ("IEX",         "Indian Energy Exchange Ltd"),
    ("IPCALAB",     "IPCA Laboratories Ltd"),
    ("IRB",         "IRB Infrastructure Developers Ltd"),
    ("JKCEMENT",    "JK Cement Ltd"),
    ("KPITTECH",    "KPIT Technologies Ltd"),
    ("KPRMILL",     "K.P.R. Mill Ltd"),
    ("LALPATHLAB",  "Dr. Lal Path Labs Ltd"),
    ("LICHSGFIN",   "LIC Housing Finance Ltd"),
    ("LUPIN",       "Lupin Ltd"),
    ("MANAPPURAM",  "Manappuram Finance Ltd"),
    ("M&MFIN",      "Mahindra & Mahindra Financial Services Ltd"),
    ("MCX",         "Multi Commodity Exchange of India Ltd"),
    ("METROPOLIS",  "Metropolis Healthcare Ltd"),
    ("MRF",         "MRF Ltd"),
    ("NATCOPHARM",  "Natco Pharma Ltd"),
    ("NAVINFLUOR",  "Navin Fluorine International Ltd"),
    ("NBCC",        "NBCC (India) Ltd"),
    ("NMDC",        "NMDC Ltd"),
    ("OFSS",        "Oracle Financial Services Software Ltd"),
    ("OIL",         "Oil India Ltd"),
    ("PAGEIND",     "Page Industries Ltd"),
    ("PHOENIXLTD",  "Phoenix Mills Ltd"),
    ("POLYCAB",     "Polycab India Ltd"),
    ("PVRINOX",     "PVR INOX Ltd"),
    ("RADICO",      "Radico Khaitan Ltd"),
    ("RBLBANK",     "RBL Bank Ltd"),
    ("ROUTE",       "Route Mobile Ltd"),
    ("SBICARD",     "SBI Cards and Payment Services Ltd"),
    ("SCHAEFFLER",  "Schaeffler India Ltd"),
    ("SOBHA",       "Sobha Ltd"),
    ("SONACOMS",    "Sona BLW Precision Forgings Ltd"),
    ("STARHEALTH",  "Star Health and Allied Insurance Company Ltd"),
    ("SUNDARMFIN",  "Sundaram Finance Ltd"),
    ("SUNDRMFAST",  "Sundram Fasteners Ltd"),
    ("SUPREMEIND",  "Supreme Industries Ltd"),
    ("SYNGENE",     "Syngene International Ltd"),
    ("THERMAX",     "Thermax Ltd"),
    ("TIINDIA",     "Tube Investments of India Ltd"),
    ("TORNTPOWER",  "Torrent Power Ltd"),
    ("TRIDENT",     "Trident Ltd"),
    ("TVSMOTOR",    "TVS Motor Company Ltd"),
    ("UNIONBANK",   "Union Bank of India"),
    ("UTIAMC",      "UTI Asset Management Company Ltd"),
    ("VINATIORGA",  "Vinati Organics Ltd"),
    ("ZEEL",        "Zee Entertainment Enterprises Ltd"),
    ("ZENSARTECH",  "Zensar Technologies Ltd"),

    # ── Nifty Smallcap & Other Actively Traded NSE Stocks ────────────────────
    ("ANGELONE",    "Angel One Ltd"),
    ("APLLTD",      "APL Apollo Tubes Ltd"),
    ("ASHOKLEY",    "Ashok Leyland Ltd"),
    ("ASTRAL",      "Astral Ltd"),
    ("BALKRISIND",  "Balkrishna Industries Ltd"),
    ("BALRAMCHIN",  "Balrampur Chini Mills Ltd"),
    ("BANDHANBNK",  "Bandhan Bank Ltd"),
    ("BANKINDIA",   "Bank of India"),
    ("BEML",        "BEML Ltd"),
    ("BHARATFORG",  "Bharat Forge Ltd"),
    ("BLUEDART",    "Blue Dart Express Ltd"),
    ("BLUESTARCO",  "Blue Star Ltd"),
    ("BRIGADE",     "Brigade Enterprises Ltd"),
    ("BSOFT",       "Birlasoft Ltd"),
    ("CANARA",      "Canara Bank"),
    ("CASTROLIND",  "Castrol India Ltd"),
    ("CDSL",        "Central Depository Services (India) Ltd"),
    ("CENTURYPLY",  "Century Plyboards (India) Ltd"),
    ("CENTURYTEX",  "Century Textiles and Industries Ltd"),
    ("CESC",        "CESC Ltd"),
    ("CHAMBLFERT",  "Chambal Fertilisers and Chemicals Ltd"),
    ("CLEAN",       "Clean Science and Technology Ltd"),
    ("COCHINSHIP",  "Cochin Shipyard Ltd"),
    ("CRISIL",      "CRISIL Ltd"),
    ("CYIENT",      "Cyient Ltd"),
    ("DCBBANK",     "DCB Bank Ltd"),
    ("DEEPAKFERT",  "Deepak Fertilisers and Petrochemicals Corporation Ltd"),
    ("DELTACORP",   "Delta Corp Ltd"),
    ("DHANUKA",     "Dhanuka Agritech Ltd"),
    ("DLF",         "DLF Ltd"),
    ("DODLA",       "Dodla Dairy Ltd"),
    ("EIDPARRY",    "EID Parry (India) Ltd"),
    ("FINCABLES",   "Finolex Cables Ltd"),
    ("FINPIPE",     "Finolex Industries Ltd"),
    ("FORTIS",      "Fortis Healthcare Ltd"),
    ("GALAXYSURF",  "Galaxy Surfactants Ltd"),
    ("GARFIBRES",   "Garware Technical Fibres Ltd"),
    ("GICRE",       "General Insurance Corporation of India"),
    ("GMRINFRA",    "GMR Airports Infrastructure Ltd"),
    ("GODREJAGRO",  "Godrej Agrovet Ltd"),
    ("GODREJIND",   "Godrej Industries Ltd"),
    ("GPIL",        "Godawari Power and Ispat Ltd"),
    ("GREAVESCOT",  "Greaves Cotton Ltd"),
    ("GRINDWELL",   "Grindwell Norton Ltd"),
    ("GSFC",        "Gujarat State Fertilizers & Chemicals Ltd"),
    ("GSPL",        "Gujarat State Petronet Ltd"),
    ("HIKAL",       "Hikal Ltd"),
    ("HIMADRI",     "Himadri Speciality Chemical Ltd"),
    ("HINDZINC",    "Hindustan Zinc Ltd"),
    ("HOMEFIRST",   "Home First Finance Company India Ltd"),
    ("IDBI",        "IDBI Bank Ltd"),
    ("IDFC",        "IDFC Ltd"),
    ("IGL",         "Indraprastha Gas Ltd"),
    ("INDHOTEL",    "The Indian Hotels Company Ltd"),
    ("INDIAMART",   "IndiaMart InterMesh Ltd"),
    ("INDIANB",     "Indian Bank"),
    ("INOXGREEN",   "INOX Green Energy Services Ltd"),
    ("INTELLECT",   "Intellect Design Arena Ltd"),
    ("IOB",         "Indian Overseas Bank"),
    ("IREDA",       "Indian Renewable Energy Development Agency Ltd"),
    ("IRFC",        "Indian Railway Finance Corporation Ltd"),
    ("JBCHEPHARM",  "JB Chemicals & Pharmaceuticals Ltd"),
    ("JIOFINANCE",  "Jio Financial Services Ltd"),
    ("JKPAPER",     "JK Paper Ltd"),
    ("JKTYRE",      "JK Tyre & Industries Ltd"),
    ("JMFINANCIL",  "JM Financial Ltd"),
    ("JSL",         "Jindal Stainless Ltd"),
    ("JSWENERGY",   "JSW Energy Ltd"),
    ("JUSTDIAL",    "Just Dial Ltd"),
    ("JYOTHYLAB",   "Jyothy Labs Ltd"),
    ("KAJARIACER",  "Kajaria Ceramics Ltd"),
    ("KALPATPOWR",  "Kalpataru Projects International Ltd"),
    ("KANSAINER",   "Kansai Nerolac Paints Ltd"),
    ("KAYNES",      "Kaynes Technology India Ltd"),
    ("KEC",         "KEC International Ltd"),
    ("KFINTECH",    "KFin Technologies Ltd"),
    ("KRBL",        "KRBL Ltd"),
    ("LAURUSLABS",  "Laurus Labs Ltd"),
    ("LEMONTREE",   "Lemon Tree Hotels Ltd"),
    ("LINDEINDIA",  "Linde India Ltd"),
    ("LUXIND",      "Lux Industries Ltd"),
    ("MAHINDLIFE",  "Mahindra Lifespace Developers Ltd"),
    ("MASTEK",      "Mastek Ltd"),
    ("MAPMYINDIA",  "CE Info Systems Ltd"),
    ("MEDPLUS",     "MedPlus Health Services Ltd"),
    ("MIDHANI",     "Mishra Dhatu Nigam Ltd"),
    ("MINDACORP",   "Minda Corporation Ltd"),
    ("MOIL",        "MOIL Ltd"),
    ("MRPL",        "Mangalore Refinery and Petrochemicals Ltd"),
    ("MSUMI",       "Motherson Sumi Wiring India Ltd"),
    ("NAVA",        "Nava Ltd"),
    ("NAVNETEDUL",  "Navneet Education Ltd"),
    ("NCC",         "NCC Ltd"),
    ("NH",          "Narayana Hrudayalaya Ltd"),
    ("NHPC",        "NHPC Ltd"),
    ("NIITLTD",     "NIIT Ltd"),
    ("NSLNISP",     "NMDC Steel Ltd"),
    ("OBEROI",      "Oberoi Realty Ltd"),
    ("OLECTRA",     "Olectra Greentech Ltd"),
    ("ORIENTCEM",   "Orient Cement Ltd"),
    ("ORIENTELEC",  "Orient Electric Ltd"),
    ("PAYTM",       "One97 Communications Ltd"),
    ("PCBL",        "PCBL Ltd"),
    ("PERSISTENT",  "Persistent Systems Ltd"),
    ("PFIZER",      "Pfizer Ltd"),
    ("PIRAMAL",     "Piramal Enterprises Ltd"),
    ("PNBHSGFIN",   "PNB Housing Finance Ltd"),
    ("POLICYBZR",   "PB Fintech Ltd"),
    ("POLYPLEX",    "Polyplex Corporation Ltd"),
    ("PRAJ",        "Praj Industries Ltd"),
    ("PRINCEPIPE",  "Prince Pipes and Fittings Ltd"),
    ("PRSMJOHNSN",  "Prism Johnson Ltd"),
    ("PSB",         "Punjab & Sind Bank"),
    ("PTC",         "PTC India Ltd"),
    ("RAYMOND",     "Raymond Ltd"),
    ("RITES",       "RITES Ltd"),
    ("RVNL",        "Rail Vikas Nigam Ltd"),
    ("SAFARI",      "Safari Industries (India) Ltd"),
    ("SAIL",        "Steel Authority of India Ltd"),
    ("SAREGAMA",    "Saregama India Ltd"),
    ("SCI",         "Shipping Corporation of India Ltd"),
    ("SHRIRAMFIN",  "Shriram Finance Ltd"),
    ("SHYAMMETL",   "Shyam Metalics and Energy Ltd"),
    ("SOLARINDS",   "Solar Industries India Ltd"),
    ("SONATSOFTW",  "Sonata Software Ltd"),
    ("SPANDANA",    "Spandana Sphoorty Financial Ltd"),
    ("SPICEJET",    "SpiceJet Ltd"),
    ("STARCEMENT",  "Star Cement Ltd"),
    ("STERLITE",    "Sterlite Technologies Ltd"),
    ("SUBROS",      "Subros Ltd"),
    ("SUMITCHEM",   "Sumitomo Chemical India Ltd"),
    ("SUNTV",       "Sun TV Network Ltd"),
    ("SUZLON",      "Suzlon Energy Ltd"),
    ("SYMPHONY",    "Symphony Ltd"),
    ("TANLA",       "Tanla Platforms Ltd"),
    ("TEAMLEASE",   "TeamLease Services Ltd"),
    ("THYROCARE",   "Thyrocare Technologies Ltd"),
    ("TTKPRESTIG",  "TTK Prestige Ltd"),
    ("UCO",         "UCO Bank"),
    ("UFLEX",       "UFLEX Ltd"),
    ("UJJIVANSFB",  "Ujjivan Small Finance Bank Ltd"),
    ("UNOMINDA",    "Uno Minda Ltd"),
    ("VAIBHAVGBL",  "Vaibhav Global Ltd"),
    ("VGUARD",      "V-Guard Industries Ltd"),
    ("VSTIND",      "VST Industries Ltd"),
    ("WABAG",       "VA Tech Wabag Ltd"),
    ("WELCORP",     "Welspun Corp Ltd"),
    ("WELSPUNIND",  "Welspun India Ltd"),
    ("WESTLIFE",    "Westlife Foodworld Ltd"),
    ("WHIRLPOOL",   "Whirlpool of India Ltd"),
    ("WINDLAS",     "Windlas Biotech Ltd"),
    ("WONDERLA",    "Wonderla Holidays Ltd"),
    ("YATHARTH",    "Yatharth Hospital & Trauma Care Services Ltd"),
    ("ZENTEC",      "Zensar Technologies Ltd"),

    # ── Banking & Finance ─────────────────────────────────────────────────────
    ("CANBK",       "Canara Bank"),
    ("EQUITASBNK",  "Equitas Small Finance Bank Ltd"),
    ("ESAFSFB",     "ESAF Small Finance Bank Ltd"),
    ("FINOLINE",    "Fino Payments Bank Ltd"),
    ("IIFLSEC",     "IIFL Securities Ltd"),
    ("IIFL",        "IIFL Finance Ltd"),
    ("JKBANK",      "Jammu & Kashmir Bank Ltd"),
    ("SURYODAY",    "Suryoday Small Finance Bank Ltd"),
    ("UJJIVAN",     "Ujjivan Financial Services Ltd"),
    ("UTKARSHBNK",  "Utkarsh Small Finance Bank Ltd"),

    # ── IT & Technology ───────────────────────────────────────────────────────
    ("HAPPSTMNDS",  "Happiest Minds Technologies Ltd"),
    ("HEXAWARE",    "Hexaware Technologies Ltd"),
    ("MPHASIS",     "Mphasis Ltd"),
    ("NIIT",        "NIIT Ltd"),
    ("RATEGAIN",    "RateGain Travel Technologies Ltd"),
    ("TATAELXSI",   "Tata Elxsi Ltd"),
    ("TRIGYN",      "Trigyn Technologies Ltd"),
    ("XCHANGING",   "Xchanging Solutions Ltd"),

    # ── Pharma & Healthcare ───────────────────────────────────────────────────
    ("ABBOTINDIA",  "Abbott India Ltd"),
    ("ASTRAZEN",    "AstraZeneca Pharma India Ltd"),
    ("GLAND",       "Gland Pharma Ltd"),
    ("GLAXO",       "GlaxoSmithKline Pharmaceuticals Ltd"),
    ("KRSNAA",      "Krsnaa Diagnostics Ltd"),
    ("SOLARA",      "Solara Active Pharma Sciences Ltd"),
    ("SUPRIYA",     "Supriya Lifescience Ltd"),
    ("SUVENPHAR",   "Suven Pharmaceuticals Ltd"),
    ("VIJAYA",      "Vijaya Diagnostic Centre Ltd"),

    # ── Auto & Auto Ancillaries ───────────────────────────────────────────────
    ("AMARAJABAT",  "Amara Raja Energy & Mobility Ltd"),
    ("ATULAUTO",    "Atul Auto Ltd"),
    ("CRAFTSMAN",   "Craftsman Automation Ltd"),
    ("GABRIEL",     "Gabriel India Ltd"),
    ("JBMA",        "JBM Auto Ltd"),
    ("MAHINDCIE",   "Mahindra CIE Automotive Ltd"),
    ("MINDAIND",    "Uno Minda Ltd"),
    ("MOTHERSON",   "Samvardhana Motherson International Ltd"),
    ("SANSERA",     "Sansera Engineering Ltd"),
    ("SUPRAJIT",    "Suprajit Engineering Ltd"),

    # ── Energy & Power ────────────────────────────────────────────────────────
    ("CESC",        "CESC Ltd"),
    ("GPIL",        "Godawari Power and Ispat Ltd"),
    ("INOXWIND",    "Inox Wind Ltd"),
    ("JPPOWER",     "Jaiprakash Power Ventures Ltd"),
    ("NPCIL",       "Nuclear Power Corporation of India Ltd"),
    ("RPOWER",      "Reliance Power Ltd"),
    ("SJVN",        "SJVN Ltd"),
    ("TPWR",        "Tata Power Company Ltd"),
    ("WAAREEENER",  "Waaree Energies Ltd"),

    # ── Infrastructure & Real Estate ──────────────────────────────────────────
    ("AHLUCONT",    "Ahluwalia Contracts (India) Ltd"),
    ("IBREALEST",   "Indiabulls Real Estate Ltd"),
    ("INFRATEL",    "Indus Towers Ltd"),
    ("INDUSTOWER",  "Indus Towers Ltd"),
    ("KOLTEPATIL",  "Kolte-Patil Developers Ltd"),
    ("NCC",         "NCC Ltd"),
    ("OMAXE",       "Omaxe Ltd"),
    ("PRESTIGE",    "Prestige Estates Projects Ltd"),
    ("SUNTECKREAL", "Sunteck Realty Ltd"),

    # ── FMCG & Retail ────────────────────────────────────────────────────────
    ("BALAMINES",   "Balaji Amines Ltd"),
    ("BIKAJI",      "Bikaji Foods International Ltd"),
    ("CAMPUS",      "Campus Activewear Ltd"),
    ("DEVYANI",     "Devyani International Ltd"),
    ("DOMS",        "DOMS Industries Ltd"),
    ("GODFRYPHLP",  "Godfrey Phillips India Ltd"),
    ("JYOTHYLAB",   "Jyothy Labs Ltd"),
    ("MCCLEODS",    "McLeod Russel India Ltd"),
    ("PATANJALI",   "Patanjali Foods Ltd"),
    ("SAPPHIRE",    "Sapphire Foods India Ltd"),
    ("TATACOFFEE",  "Tata Coffee Ltd"),
    ("UNITDSPR",    "United Spirits Ltd"),
    ("VSTIND",      "VST Industries Ltd"),
    ("ZYDUSWELL",   "Zydus Wellness Ltd"),

    # ── Chemicals & Fertilisers ───────────────────────────────────────────────
    ("APCOTEXIND",  "Apcotex Industries Ltd"),
    ("BASF",        "BASF India Ltd"),
    ("GNFC",        "Gujarat Narmada Valley Fertilizers & Chemicals Ltd"),
    ("NAVNETEDUL",  "Navneet Education Ltd"),
    ("NOCIL",       "NOCIL Ltd"),
    ("PARAS",       "Paras Defence and Space Technologies Ltd"),
    ("PARADEEP",    "Paradeep Phosphates Ltd"),
    ("ROSSARI",     "Rossari Biotech Ltd"),

    # ── Defence & PSU ─────────────────────────────────────────────────────────
    ("BDL",         "Bharat Dynamics Ltd"),
    ("ENGINERSIN",  "Engineers India Ltd"),
    ("ITI",         "ITI Ltd"),
    ("MAZAGON",     "Mazagon Dock Shipbuilders Ltd"),
    ("MISRALMT",    "Mishra Dhatu Nigam Ltd"),
    ("NFL",         "National Fertilizers Ltd"),

    # ── Logistics & Shipping ──────────────────────────────────────────────────
    ("MAHLOG",      "Mahindra Logistics Ltd"),
    ("TCI",         "Transport Corporation of India Ltd"),
    ("TCIEXP",      "TCI Express Ltd"),

    # ── Media & Entertainment ─────────────────────────────────────────────────
    ("NETWORK18",   "Network18 Media & Investments Ltd"),
    ("PVR",         "PVR INOX Ltd"),
    ("SUNTV",       "Sun TV Network Ltd"),

    # ── Gems, Jewellery & Textiles ───────────────────────────────────────────
    ("KALYAN",      "Kalyan Jewellers India Ltd"),
    ("PCJEWELLER",  "PC Jeweller Ltd"),
    ("RAYMOND",     "Raymond Ltd"),
    ("RELAXO",      "Relaxo Footwears Ltd"),
    ("SENATOR",     "Senator Footwear Ltd"),
    ("SENCO",       "Senco Gold Ltd"),
    ("VMART",       "V-Mart Retail Ltd"),
]
